//! Generated gateway bootstrap for sdkwork-invoice.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_invoice_service_host::InvoiceServiceHost;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router(host: Arc<InvoiceServiceHost>) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_invoice_app_api::gateway_mount(host.clone()).await);
    router = router.merge(sdkwork_routes_invoice_backend_api::gateway_mount(host).await);
    ApplicationAssembly { router }
}
